### ISSUE TITLE
question regarding "fit data"

### ISSUE THREAD

**Issue by orenmizr** [ankane/disco-node#1]
hi, i have a question not an issue. 
in the example you loaded the movie db into the recommender class so it will gain the rec insight. how can you do it if you a lot of data  in the db (runtime memory usage is high)?  does one need to unload all the db into the rec  node runtime ?  

10x

**Comment by ankane** [comment]
Hi @orenmizr, yes, all of the data needs to be loaded at once. You'll need to use a different library if your data won't fit into memory.

**Comment by orenmizr** [comment]
what are the limitations ? millions of records, a certain byte size ? how does one know ?
